import { Product } from '@/types/product';

export const mockInventory: Product[] = [
  {
    id: 1,
    image: "https://picsum.photos/id/1/800/800",
    name: "Product Alpha",
    category: "Category A",
    price: 19.99,
    currency: "USD",
    review_count: 5,
    review_sum: 4.6,
  },
  {
    id: 2,
    image: "https://picsum.photos/id/2/800/800",
    name: "Product Beta",
    category: "Category B",
    price: 29.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4,
  },
  {
    id: 3,
    image: "https://picsum.photos/id/3/800/800",
    name: "Product Gamma",
    category: "Category C",
    price: 39.99,
    currency: "USD",
    review_count: 12,
    review_sum: 4,
  },
  {
    id: 4,
    image: "https://picsum.photos/id/4/800/800",
    name: "Product Delta",
    category: "Category D",
    price: 49.99,
    currency: "USD",
    review_count: 4,
    review_sum: 5,
  },
  {
    id: 5,
    image: "https://picsum.photos/id/5/800/800",
    name: "Product Epsilon",
    category: "Category E",
    price: 59.99,
    currency: "USD",
    review_count: 10,
    review_sum: 3.6,
  },
  {
    id: 6,
    image: "https://picsum.photos/id/6/800/800",
    name: "Product Zeta",
    category: "Category F",
    price: 69.99,
    currency: "USD",
    review_count: 7,
    review_sum: 4,
  },
  {
    id: 7,
    image: "https://picsum.photos/id/7/800/800",
    name: "Product Eta",
    category: "Category G",
    price: 79.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.7,
  },
  {
    id: 8,
    image: "https://picsum.photos/id/8/800/800",
    name: "Product Theta",
    category: "Category H",
    price: 89.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4,
  },
  {
    id: 9,
    image: "https://picsum.photos/id/9/800/800",
    name: "Product Iota",
    category: "Category I",
    price: 99.99,
    currency: "USD",
    review_count: 4,
    review_sum: 4.5,
  },
  {
    id: 10,
    image: "https://picsum.photos/id/10/800/800",
    name: "Product Kappa",
    category: "Category J",
    price: 109.99,
    currency: "USD",
    review_count: 5,
    review_sum: 4.4,
  },
  {
    id: 11,
    image: "https://picsum.photos/id/11/800/800",
    name: "Product Lambda",
    category: "Category K",
    price: 119.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4.4,
  },
  {
    id: 12,
    image: "https://picsum.photos/id/12/800/800",
    name: "Product Mu",
    category: "Category L",
    price: 129.99,
    currency: "USD",
    review_count: 10,
    review_sum: 4,
  },
  {
    id: 13,
    image: "https://picsum.photos/id/13/800/800",
    name: "Product Nu",
    category: "Category M",
    price: 139.99,
    currency: "USD",
    review_count: 12,
    review_sum: 4,
  },
  {
    id: 14,
    image: "https://picsum.photos/id/14/800/800",
    name: "Product Xi",
    category: "Category N",
    price: 149.99,
    currency: "USD",
    review_count: 7,
    review_sum: 3.9,
  },
  {
    id: 15,
    image: "https://picsum.photos/id/15/800/800",
    name: "Product Omicron",
    category: "Category O",
    price: 159.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.6,
  },
  {
    id: 16,
    image: "https://picsum.photos/id/16/800/800",
    name: "Product Pi",
    category: "Category P",
    price: 169.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4,
  },
  {
    id: 17,
    image: "https://picsum.photos/id/17/800/800",
    name: "Product Rho",
    category: "Category Q",
    price: 179.99,
    currency: "USD",
    review_count: 5,
    review_sum: 4.6,
  },
  {
    id: 18,
    image: "https://picsum.photos/id/18/800/800",
    name: "Product Sigma",
    category: "Category R",
    price: 189.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4.3,
  },
  {
    id: 19,
    image: "https://picsum.photos/id/19/800/800",
    name: "Product Tau",
    category: "Category S",
    price: 199.99,
    currency: "USD",
    review_count: 7,
    review_sum: 4.1,
  },
  {
    id: 20,
    image: "https://picsum.photos/id/20/800/800",
    name: "Product Upsilon",
    category: "Category T",
    price: 209.99,
    currency: "USD",
    review_count: 10,
    review_sum: 4.1,
  },
  {
    id: 21,
    image: "https://picsum.photos/id/21/800/800",
    name: "Product Phi",
    category: "Category U",
    price: 219.99,
    currency: "USD",
    review_count: 12,
    review_sum: 4,
  },
  {
    id: 22,
    image: "https://picsum.photos/id/22/800/800",
    name: "Product Chi",
    category: "Category V",
    price: 229.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.6,
  },
  {
    id: 23,
    image: "https://picsum.photos/id/23/800/800",
    name: "Product Psi",
    category: "Category W",
    price: 239.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4.2,
  },
  {
    id: 24,
    image: "https://picsum.photos/id/24/800/800",
    name: "Product Omega",
    category: "Category X",
    price: 249.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4.3,
  },
  {
    id: 25,
    image: "https://picsum.photos/id/25/800/800",
    name: "Product Alpha-2",
    category: "Category Y",
    price: 259.99,
    currency: "USD",
    review_count: 10,
    review_sum: 4,
  },
  {
    id: 26,
    image: "https://picsum.photos/id/26/800/800",
    name: "Product Beta-2",
    category: "Category Z",
    price: 269.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.7,
  },
  {
    id: 27,
    image: "https://picsum.photos/id/27/800/800",
    name: "Product Gamma-2",
    category: "Category AA",
    price: 279.99,
    currency: "USD",
    review_count: 7,
    review_sum: 4,
  },
  {
    id: 28,
    image: "https://picsum.photos/id/28/800/800",
    name: "Product Delta-2",
    category: "Category BB",
    price: 289.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4,
  },
  {
    id: 29,
    image: "https://picsum.photos/id/29/800/800",
    name: "Product Epsilon-2",
    category: "Category CC",
    price: 299.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4,
  },
  {
    id: 30,
    image: "https://picsum.photos/id/30/800/800",
    name: "Product Zeta-2",
    category: "Category DD",
    price: 309.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.9,
  },
  {
    id: 31,
    image: "https://picsum.photos/id/31/800/800",
    name: "Product Eta-2",
    category: "Category EE",
    price: 319.99,
    currency: "USD",
    review_count: 10,
    review_sum: 4,
  },
  {
    id: 32,
    image: "https://picsum.photos/id/32/800/800",
    name: "Product Theta-2",
    category: "Category FF",
    price: 329.99,
    currency: "USD",
    review_count: 7,
    review_sum: 4,
  },
  {
    id: 33,
    image: "https://picsum.photos/id/33/800/800",
    name: "Product Iota-2",
    category: "Category GG",
    price: 339.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4,
  },
  {
    id: 34,
    image: "https://picsum.photos/id/34/800/800",
    name: "Product Kappa-2",
    category: "Category HH",
    price: 349.99,
    currency: "USD",
    review_count: 5,
    review_sum: 4.6,
  },
  {
    id: 35,
    image: "https://picsum.photos/id/35/800/800",
    name: "Product Lambda-2",
    category: "Category II",
    price: 359.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4,
  },
  {
    id: 36,
    image: "https://picsum.photos/id/36/800/800",
    name: "Product Mu-2",
    category: "Category JJ",
    price: 369.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.9,
  },
  {
    id: 37,
    image: "https://picsum.photos/id/37/800/800",
    name: "Product Nu-2",
    category: "Category KK",
    price: 379.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4,
  },
  {
    id: 38,
    image: "https://picsum.photos/id/38/800/800",
    name: "Product Xi-2",
    category: "Category LL",
    price: 389.99,
    currency: "USD",
    review_count: 7,
    review_sum: 4,
  },
  {
    id: 39,
    image: "https://picsum.photos/id/39/800/800",
    name: "Product Omicron-2",
    category: "Category MM",
    price: 399.99,
    currency: "USD",
    review_count: 9,
    review_sum: 3.6,
  },
  {
    id: 40,
    image: "https://picsum.photos/id/40/800/800",
    name: "Product Pi-2",
    category: "Category NN",
    price: 409.99,
    currency: "USD",
    review_count: 6,
    review_sum: 4,
  },
  {
    id: 41,
    image: "https://picsum.photos/id/41/800/800",
    name: "Product Rho-2",
    category: "Category OO",
    price: 419.99,
    currency: "USD",
    review_count: 5,
    review_sum: 4.6,
  },
  {
    id: 42,
    image: "https://picsum.photos/id/42/800/800",
    name: "Product Sigma-1",
    category: "Category PP",
    price: 429.99,
    currency: "USD",
    review_count: 8,
    review_sum: 4,
  },
  {
    id: 43,
    image: "https://picsum.photos/id/43/800/800",
    name: "Product Tau-1",
    category: "Category QQ",
    price: 439.99,
    currency: "USD",
    review_count: 7,
    review_sum: 3.9,
  },
  {
    id: 44,
    image: "https://picsum.photos/id/44/800/800",
    name: "Product Upsilon-1",
    category: "Category RR",
    price: 449.99,
    currency: "USD",
    review_count: 10,
    review_sum: 4,
  },
];
