import { Product } from '@/types/product';

export const mockInventory: Product[] = [
  {
    id: 1,
    image: "https://picsum.photos/id/1/200/200",
    name: "Classic White Sneakers",
    category: "Shoes",
    price: 899,
    currency: "SEK",
    review_count: 24,
    review_sum: 96,
  },
  {
    id: 2,
    image: "https://picsum.photos/id/2/200/200",
    name: "Running Shoes Pro",
    category: "Shoes",
    price: 1299,
    currency: "SEK",
    review_count: 18,
    review_sum: 78,
  },
  {
    id: 3,
    image: "https://picsum.photos/id/3/200/200",
    name: "Leather Boots",
    category: "Shoes",
    price: 1599,
    currency: "SEK",
    review_count: 31,
    review_sum: 134,
  },
  {
    id: 4,
    image: "https://picsum.photos/id/4/200/200",
    name: "Canvas Slip-Ons",
    category: "Shoes",
    price: 499,
    currency: "SEK",
    review_count: 12,
    review_sum: 48,
  },
  {
    id: 5,
    image: "https://picsum.photos/id/5/200/200",
    name: "Hiking Boots",
    category: "Shoes",
    price: 1899,
    currency: "SEK",
    review_count: 42,
    review_sum: 175,
  },
  {
    id: 6,
    image: "https://picsum.photos/id/6/200/200",
    name: "Wool Knit Sweater",
    category: "Clothing",
    price: 699,
    currency: "SEK",
    review_count: 15,
    review_sum: 63,
  },
  {
    id: 7,
    image: "https://picsum.photos/id/7/200/200",
    name: "Slim Fit Jeans",
    category: "Clothing",
    price: 549,
    currency: "SEK",
    review_count: 28,
    review_sum: 118,
  },
  {
    id: 8,
    image: "https://picsum.photos/id/8/200/200",
    name: "Cotton T-Shirt",
    category: "Clothing",
    price: 199,
    currency: "SEK",
    review_count: 56,
    review_sum: 230,
  },
  {
    id: 9,
    image: "https://picsum.photos/id/9/200/200",
    name: "Waterproof Jacket",
    category: "Clothing",
    price: 1499,
    currency: "SEK",
    review_count: 22,
    review_sum: 92,
  },
  {
    id: 10,
    image: "https://picsum.photos/id/10/200/200",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 1299,
    currency: "SEK",
    review_count: 67,
    review_sum: 280,
  },
  {
    id: 11,
    image: "https://picsum.photos/id/11/200/200",
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 799,
    currency: "SEK",
    review_count: 34,
    review_sum: 140,
  },
  {
    id: 12,
    image: "https://picsum.photos/id/12/200/200",
    name: "Smart Watch",
    category: "Electronics",
    price: 2499,
    currency: "SEK",
    review_count: 45,
    review_sum: 190,
  },
  {
    id: 13,
    image: "https://picsum.photos/id/13/200/200",
    name: "USB-C Cable 2m",
    category: "Electronics",
    price: 149,
    currency: "SEK",
    review_count: 89,
    review_sum: 360,
  },
  {
    id: 14,
    image: "https://picsum.photos/id/14/200/200",
    name: "Portable Charger 20000mAh",
    category: "Electronics",
    price: 399,
    currency: "SEK",
    review_count: 52,
    review_sum: 215,
  },
  {
    id: 15,
    image: "https://picsum.photos/id/15/200/200",
    name: "Yoga Mat",
    category: "Sports",
    price: 299,
    currency: "SEK",
    review_count: 19,
    review_sum: 80,
  },
  {
    id: 16,
    image: "https://picsum.photos/id/16/200/200",
    name: "Dumbbells 10kg Pair",
    category: "Sports",
    price: 499,
    currency: "SEK",
    review_count: 27,
    review_sum: 112,
  },
  {
    id: 17,
    image: "https://picsum.photos/id/17/200/200",
    name: "Tennis Racket",
    category: "Sports",
    price: 899,
    currency: "SEK",
    review_count: 14,
    review_sum: 58,
  },
  {
    id: 18,
    image: "https://picsum.photos/id/18/200/200",
    name: "Camping Tent 4-Person",
    category: "Sports",
    price: 1999,
    currency: "SEK",
    review_count: 33,
    review_sum: 138,
  },
  {
    id: 19,
    image: "https://picsum.photos/id/19/200/200",
    name: "Ceramic Coffee Mug",
    category: "Home",
    price: 89,
    currency: "SEK",
    review_count: 71,
    review_sum: 290,
  },
  {
    id: 20,
    image: "https://picsum.photos/id/20/200/200",
    name: "Scented Candle Set",
    category: "Home",
    price: 199,
    currency: "SEK",
    review_count: 38,
    review_sum: 155,
  },
  {
    id: 21,
    image: "https://picsum.photos/id/21/200/200",
    name: "Bamboo Cutting Board",
    category: "Home",
    price: 149,
    currency: "SEK",
    review_count: 25,
    review_sum: 102,
  },
  {
    id: 22,
    image: "https://picsum.photos/id/22/200/200",
    name: "Stainless Steel Water Bottle",
    category: "Home",
    price: 249,
    currency: "SEK",
    review_count: 44,
    review_sum: 180,
  },
  {
    id: 23,
    image: "https://picsum.photos/id/23/200/200",
    name: "Desk Lamp LED",
    category: "Home",
    price: 399,
    currency: "SEK",
    review_count: 16,
    review_sum: 66,
  },
  {
    id: 24,
    image: "https://picsum.photos/id/24/200/200",
    name: "Running Shoes Elite",
    category: "Shoes",
    price: 1699,
    currency: "SEK",
    review_count: 50,
    review_sum: 210,
  },
  {
    id: 25,
    image: "https://picsum.photos/id/25/200/200",
    name: "Sandals Summer",
    category: "Shoes",
    price: 399,
    currency: "SEK",
    review_count: 21,
    review_sum: 88,
  },
  {
    id: 26,
    image: "https://picsum.photos/id/26/200/200",
    name: "High Heels Classic",
    category: "Shoes",
    price: 1199,
    currency: "SEK",
    review_count: 17,
    review_sum: 70,
  },
  {
    id: 27,
    image: "https://picsum.photos/id/27/200/200",
    name: "Winter Boots Insulated",
    category: "Shoes",
    price: 1399,
    currency: "SEK",
    review_count: 39,
    review_sum: 160,
  },
  {
    id: 28,
    image: "https://picsum.photos/id/28/200/200",
    name: "Loafers Leather",
    category: "Shoes",
    price: 999,
    currency: "SEK",
    review_count: 23,
    review_sum: 95,
  },
  {
    id: 29,
    image: "https://picsum.photos/id/29/200/200",
    name: "Pullover Hoodie",
    category: "Clothing",
    price: 499,
    currency: "SEK",
    review_count: 41,
    review_sum: 168,
  },
  {
    id: 30,
    image: "https://picsum.photos/id/30/200/200",
    name: "Chino Pants",
    category: "Clothing",
    price: 449,
    currency: "SEK",
    review_count: 29,
    review_sum: 120,
  },
  {
    id: 31,
    image: "https://picsum.photos/id/31/200/200",
    name: "Earbuds Wireless",
    category: "Electronics",
    price: 999,
    currency: "SEK",
    review_count: 58,
    review_sum: 240,
  },
  {
    id: 32,
    image: "https://picsum.photos/id/32/200/200",
    name: "Fitness Tracker",
    category: "Electronics",
    price: 699,
    currency: "SEK",
    review_count: 36,
    review_sum: 148,
  },
  {
    id: 33,
    image: "https://picsum.photos/id/33/200/200",
    name: "Basketball",
    category: "Sports",
    price: 299,
    currency: "SEK",
    review_count: 20,
    review_sum: 84,
  },
  {
    id: 34,
    image: "https://picsum.photos/id/34/200/200",
    name: "Throw Blanket",
    category: "Home",
    price: 349,
    currency: "SEK",
    review_count: 32,
    review_sum: 132,
  },
  {
    id: 35,
    image: "https://picsum.photos/id/35/200/200",
    name: "Platform Sneakers",
    category: "Shoes",
    price: 1099,
    currency: "SEK",
    review_count: 26,
    review_sum: 108,
  },
  {
    id: 36,
    image: "https://picsum.photos/id/36/200/200",
    name: "Chelsea Boots",
    category: "Shoes",
    price: 1499,
    currency: "SEK",
    review_count: 35,
    review_sum: 145,
  },
  {
    id: 37,
    image: "https://picsum.photos/id/37/200/200",
    name: "Flip Flops Beach",
    category: "Shoes",
    price: 149,
    currency: "SEK",
    review_count: 48,
    review_sum: 195,
  },
  {
    id: 38,
    image: "https://picsum.photos/id/38/200/200",
    name: "Formal Dress Shirt",
    category: "Clothing",
    price: 399,
    currency: "SEK",
    review_count: 18,
    review_sum: 75,
  },
  {
    id: 39,
    image: "https://picsum.photos/id/39/200/200",
    name: "Tablet Stand Adjustable",
    category: "Electronics",
    price: 249,
    currency: "SEK",
    review_count: 13,
    review_sum: 54,
  },
  {
    id: 40,
    image: "https://picsum.photos/id/40/200/200",
    name: "Resistance Bands Set",
    category: "Sports",
    price: 199,
    currency: "SEK",
    review_count: 24,
    review_sum: 98,
  },
  {
    id: 41,
    image: "https://picsum.photos/id/41/200/200",
    name: "Picture Frame Set",
    category: "Home",
    price: 179,
    currency: "SEK",
    review_count: 11,
    review_sum: 45,
  },
  {
    id: 42,
    image: "https://picsum.photos/id/42/200/200",
    name: "Skate Shoes Urban",
    category: "Shoes",
    price: 799,
    currency: "SEK",
    review_count: 30,
    review_sum: 125,
  },
  {
    id: 43,
    image: "https://picsum.photos/id/43/200/200",
    name: "Ankle Boots Suede",
    category: "Shoes",
    price: 1299,
    currency: "SEK",
    review_count: 27,
    review_sum: 112,
  },
  {
    id: 44,
    image: "https://picsum.photos/id/44/200/200",
    name: "V-Neck Sweater",
    category: "Clothing",
    price: 599,
    currency: "SEK",
    review_count: 22,
    review_sum: 90,
  },
];
