import { Product } from '@/types/product';

export const mockInventory: Product[] = [
  {
    id: 1,
    name: "Product Alpha",
    category: "Category A",
    price: 19.99,
    currency: "USD",
    review_count: 5,
    review_sum: 23,
  },
  {
    id: 2,
    name: "Product Beta",
    category: "Category B",
    price: 29.99,
    currency: "USD",
    review_count: 8,
    review_sum: 32,
  },
  {
    id: 3,
    name: "Product Gamma",
    category: "Category C",
    price: 39.99,
    currency: "USD",
    review_count: 12,
    review_sum: 48,
  },
  {
    id: 4,
    name: "Product Delta",
    category: "Category D",
    price: 49.99,
    currency: "USD",
    review_count: 4,
    review_sum: 20,
  },
  {
    id: 5,
    name: "Product Epsilon",
    category: "Category E",
    price: 59.99,
    currency: "USD",
    review_count: 10,
    review_sum: 36,
  },
  {
    id: 6,
    name: "Product Zeta",
    category: "Category F",
    price: 69.99,
    currency: "USD",
    review_count: 7,
    review_sum: 28,
  },
  {
    id: 7,
    name: "Product Eta",
    category: "Category G",
    price: 79.99,
    currency: "USD",
    review_count: 9,
    review_sum: 33,
  },
  {
    id: 8,
    name: "Product Theta",
    category: "Category H",
    price: 89.99,
    currency: "USD",
    review_count: 6,
    review_sum: 24,
  },
  {
    id: 9,
    name: "Product Iota",
    category: "Category I",
    price: 99.99,
    currency: "USD",
    review_count: 4,
    review_sum: 18,
  },
  {
    id: 10,
    name: "Product Kappa",
    category: "Category J",
    price: 109.99,
    currency: "USD",
    review_count: 5,
    review_sum: 22,
  },
  {
    id: 11,
    name: "Product Lambda",
    category: "Category K",
    price: 119.99,
    currency: "USD",
    review_count: 8,
    review_sum: 35,
  },
  {
    id: 12,
    name: "Product Mu",
    category: "Category L",
    price: 129.99,
    currency: "USD",
    review_count: 10,
    review_sum: 40,
  },
  {
    id: 13,
    name: "Product Nu",
    category: "Category M",
    price: 139.99,
    currency: "USD",
    review_count: 12,
    review_sum: 48,
  },
  {
    id: 14,
    name: "Product Xi",
    category: "Category N",
    price: 149.99,
    currency: "USD",
    review_count: 7,
    review_sum: 27,
  },
  {
    id: 15,
    name: "Product Omicron",
    category: "Category O",
    price: 159.99,
    currency: "USD",
    review_count: 9,
    review_sum: 32,
  },
  {
    id: 16,
    name: "Product Pi",
    category: "Category P",
    price: 169.99,
    currency: "USD",
    review_count: 6,
    review_sum: 24,
  },
  {
    id: 17,
    name: "Product Rho",
    category: "Category Q",
    price: 179.99,
    currency: "USD",
    review_count: 5,
    review_sum: 23,
  },
  {
    id: 18,
    name: "Product Sigma",
    category: "Category R",
    price: 189.99,
    currency: "USD",
    review_count: 8,
    review_sum: 34,
  },
  {
    id: 19,
    name: "Product Tau",
    category: "Category S",
    price: 199.99,
    currency: "USD",
    review_count: 7,
    review_sum: 29,
  },
  {
    id: 20,
    name: "Product Upsilon",
    category: "Category T",
    price: 209.99,
    currency: "USD",
    review_count: 10,
    review_sum: 41,
  },
  {
    id: 21,
    name: "Product Phi",
    category: "Category U",
    price: 219.99,
    currency: "USD",
    review_count: 12,
    review_sum: 48,
  },
  {
    id: 22,
    name: "Product Chi",
    category: "Category V",
    price: 229.99,
    currency: "USD",
    review_count: 9,
    review_sum: 32,
  },
  {
    id: 23,
    name: "Product Psi",
    category: "Category W",
    price: 239.99,
    currency: "USD",
    review_count: 6,
    review_sum: 25,
  },
  {
    id: 24,
    name: "Product Omega",
    category: "Category X",
    price: 249.99,
    currency: "USD",
    review_count: 8,
    review_sum: 34,
  },
  {
    id: 25,
    name: "Product Alpha-2",
    category: "Category Y",
    price: 259.99,
    currency: "USD",
    review_count: 10,
    review_sum: 40,
  },
  {
    id: 26,
    name: "Product Beta-2",
    category: "Category Z",
    price: 269.99,
    currency: "USD",
    review_count: 9,
    review_sum: 33,
  },
  {
    id: 27,
    name: "Product Gamma-2",
    category: "Category AA",
    price: 279.99,
    currency: "USD",
    review_count: 7,
    review_sum: 28,
  },
  {
    id: 28,
    name: "Product Delta-2",
    category: "Category BB",
    price: 289.99,
    currency: "USD",
    review_count: 6,
    review_sum: 24,
  },
  {
    id: 29,
    name: "Product Epsilon-2",
    category: "Category CC",
    price: 299.99,
    currency: "USD",
    review_count: 8,
    review_sum: 32,
  },
  {
    id: 30,
    name: "Product Zeta-2",
    category: "Category DD",
    price: 309.99,
    currency: "USD",
    review_count: 9,
    review_sum: 35,
  },
  {
    id: 31,
    name: "Product Eta-2",
    category: "Category EE",
    price: 319.99,
    currency: "USD",
    review_count: 10,
    review_sum: 40,
  },
  {
    id: 32,
    name: "Product Theta-2",
    category: "Category FF",
    price: 329.99,
    currency: "USD",
    review_count: 7,
    review_sum: 28,
  },
  {
    id: 33,
    name: "Product Iota-2",
    category: "Category GG",
    price: 339.99,
    currency: "USD",
    review_count: 6,
    review_sum: 24,
  },
  {
    id: 34,
    name: "Product Kappa-2",
    category: "Category HH",
    price: 349.99,
    currency: "USD",
    review_count: 5,
    review_sum: 23,
  },
  {
    id: 35,
    name: "Product Lambda-2",
    category: "Category II",
    price: 359.99,
    currency: "USD",
    review_count: 8,
    review_sum: 32,
  },
  {
    id: 36,
    name: "Product Mu-2",
    category: "Category JJ",
    price: 369.99,
    currency: "USD",
    review_count: 9,
    review_sum: 35,
  },
  {
    id: 37,
    name: "Product Nu-2",
    category: "Category KK",
    price: 379.99,
    currency: "USD",
    review_count: 6,
    review_sum: 24,
  },
  {
    id: 38,
    name: "Product Xi-2",
    category: "Category LL",
    price: 389.99,
    currency: "USD",
    review_count: 7,
    review_sum: 28,
  },
  {
    id: 39,
    name: "Product Omicron-2",
    category: "Category MM",
    price: 399.99,
    currency: "USD",
    review_count: 9,
    review_sum: 32,
  },
  {
    id: 40,
    name: "Product Pi-2",
    category: "Category NN",
    price: 409.99,
    currency: "USD",
    review_count: 6,
    review_sum: 24,
  },
  {
    id: 41,
    name: "Product Rho-2",
    category: "Category OO",
    price: 419.99,
    currency: "USD",
    review_count: 5,
    review_sum: 23,
  },
  {
    id: 42,
    name: "Product Sigma-1",
    category: "Category PP",
    price: 429.99,
    currency: "USD",
    review_count: 8,
    review_sum: 32,
  },
  {
    id: 43,
    name: "Product Tau-1",
    category: "Category QQ",
    price: 439.99,
    currency: "USD",
    review_count: 7,
    review_sum: 27,
  },
  {
    id: 44,
    name: "Product Upsilon-1",
    category: "Category RR",
    price: 449.99,
    currency: "USD",
    review_count: 10,
    review_sum: 40,
  },
];
